<start> ::= <выражение>
<выражение> ::= <выражение> "+" <слагаемое> | <выражение> "-" <слагаемое> | <слагаемое>
<слагаемое> ::= <слагаемое> "*" <множитель> |  <слагаемое> "/" <множитель> | <множитель>
<множитель> ::= <число> | "(" <выражение> ")"
<число> ::= <цифра> <число> | <цифра>
<цифра> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"