<старт> ::= <выражение>
<выражение> ::= <слагаемое> | <выражение> '+' <слагаемое> | <выражение> '-' <слагаемое>
<слагаемое> ::= <множитель> | <слагаемое> '*' <множитель> | <слагаемое> '/' <множитель>
<множитель> ::= <число> | '(' <выражение> ')'
<число> ::= '-' <натуральное число> | <натуральное число>
<натуральное число> ::= <цифра> | <цифра> <натуральное число>
<цифра> ::= '0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'
